import java.awt.event.MouseEvent;
import java.util.jar.JarFile;

import java.sql.*;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author eslam
 */
public class Fram4 extends javax.swing.JFrame {
    
    public Fram4() {
        initComponents();
        setSize(1155, 720);
        setResizable(false);
        setLocation(280,100);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        first_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        passport = new javax.swing.JTextField();
        user_name = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        place = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        second_table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        first_table.setBackground(new java.awt.Color(0, 51, 153));
        first_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        first_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "User name", "phone", "passport"
            }
        ));
        first_table.setToolTipText("");
        first_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                first_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(first_table);
        first_table.getAccessibleContext().setAccessibleName("first_table");

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 530, 163);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 190, 29, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("passport:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 316, 100, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("user name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 253, 100, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("place:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 397, 80, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Date:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 441, 80, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("time:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 486, 60, 21);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("price:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 528, 80, 22);

        jButton1.setText("insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 593, 73, 23);

        jButton2.setText("delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(121, 593, 73, 23);

        jButton3.setText("update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(269, 593, 91, 23);

        jButton4.setText("show data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(419, 593, 93, 23);

        ID.setEnabled(false);
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID);
        ID.setBounds(160, 190, 163, 29);

        passport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passportActionPerformed(evt);
            }
        });
        getContentPane().add(passport);
        passport.setBounds(160, 310, 163, 27);
        getContentPane().add(user_name);
        user_name.setBounds(160, 250, 163, 30);
        getContentPane().add(time);
        time.setBounds(160, 480, 163, 27);
        getContentPane().add(date);
        date.setBounds(160, 440, 163, 30);
        getContentPane().add(price);
        price.setBounds(160, 530, 163, 28);
        getContentPane().add(place);
        place.setBounds(160, 400, 163, 26);

        second_table.setBackground(new java.awt.Color(0, 51, 102));
        second_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        second_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Place", "Price", "Date", "Time", "id", "psssport"
            }
        ));
        second_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                second_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(second_table);
        second_table.getAccessibleContext().setAccessibleName("second_table");

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(530, 0, 590, 163);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("phone number:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 355, 130, 25);
        getContentPane().add(phone);
        phone.setBounds(160, 350, 163, 28);

        jButton5.setText("back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(886, 593, 73, 23);

        jButton6.setText("surch");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(569, 249, 73, 23);

        jLabel9.setText("If you want to surch put passport only");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(569, 198, 210, 29);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder/Slide1.JPG"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-40, -10, 1180, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/airport","root","root");
        PreparedStatement prep=con.prepareStatement("insert into userdata(username,phone,passport_number)values(?,?,?)");
        PreparedStatement prep2=con.prepareStatement("insert into user_order(place,price,date_reserved,time_reserved,passport_num)values(?,?,?,?,?)");
        String place=this.place.getText();
        String price=this.price.getText();
        String Date=date.getText();
        String time=this.time.getText();
        String passport=this.passport.getText();
        String username=this.user_name.getText();
        String phone=this.phone.getText();
       //insert in the first table
        prep.setString(1, username);
        prep.setString(2, phone);
        prep.setString(3, passport);
        
        //insert in the second table
        prep2.setString(1, place);
        prep2.setString(2, price);
        prep2.setString(3, Date);
        prep2.setString(4, time);
        prep2.setString(5, passport);
        prep.executeUpdate();
        prep2.executeUpdate();
        jButton4ActionPerformed(evt);
        } catch (SQLException ex) {
            //Logger.getLogger(Fram4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
           
       Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/airport","root","root");
       PreparedStatement prep=con.prepareStatement("delete from userdata where passport_number=?");
       PreparedStatement prep2=con.prepareStatement("delete from user_order where id_num=?");
       String id_num=this.ID.getText();
       String passport=this.passport.getText();
             
       prep.setString(1, passport);       

       prep2.setString(1, id_num);       

       prep2.executeUpdate();
       prep.executeUpdate();
       jButton4ActionPerformed(evt);
        
        } catch (SQLException ex) {
            System.out.println("Error");
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

      try{
       Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/airport","root","root");
       PreparedStatement prep=con.prepareStatement("select*from userdata");
       ResultSet set=prep.executeQuery();
       DefaultTableModel table=new DefaultTableModel();
       table.addColumn("Name");
       table.addColumn("phone");
       table.addColumn("passport number");
       
       while(set.next())
       {
       String row[]={set.getString(1),set.getString(2),set.getString(3)}; 
       table.addRow(row);
       }
       first_table.setModel(table);
       ///////////////////////////////////
       PreparedStatement ps2 = con.prepareStatement("select*from user_order");
       ResultSet set2= ps2.executeQuery();
       DefaultTableModel table2=new DefaultTableModel();
       table2.addColumn("place");
       table2.addColumn("price");
       table2.addColumn("Date");
       table2.addColumn("Time");
       table2.addColumn("ID");
       table2.addColumn("passport");
       while(set2.next())
       {
       String row2[]={set2.getString(1),set2.getString(2),set2.getString(3),set2.getString(4),set2.getString(5),set2.getString(6)};
       table2.addRow(row2);
       }
       second_table.setModel(table2);
       
       } catch (SQLException ex) {
            //Logger.getLogger(Fram4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error");
       }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void first_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_first_tableMouseClicked
        // TODO add your handling code here:
        
        int rowNum_first_table=first_table.getSelectedRow();
        int row_num_sec_table;
        //Frist table when sellection.
       
        String name=first_table.getValueAt(rowNum_first_table, 0).toString();
        String phone=first_table.getValueAt(rowNum_first_table,1).toString();
        String passport=first_table.getValueAt(rowNum_first_table,2).toString();

        user_name.setText(name);
        this.passport.setText(passport);
        this.phone.setText(phone);
        
        ///second table->  ↓
        for (int i=0;;i++)
        {
        if(passport.equals(second_table.getValueAt(i, 5).toString()))
        {
        row_num_sec_table=i;
        break;
        }     
        }
     
        String place=second_table.getValueAt(row_num_sec_table, 0).toString();
        String price=second_table.getValueAt(row_num_sec_table, 1).toString();
        String Date=second_table.getValueAt(row_num_sec_table, 2).toString();
        String time=second_table.getValueAt(row_num_sec_table, 3).toString();
        String id_num=second_table.getValueAt(row_num_sec_table,4).toString();
        
        ID.setText(id_num);
        this.place.setText(place);
        this.date.setText(Date);
        this.time.setText(time);
        this.price.setText(price); 
        
    }//GEN-LAST:event_first_tableMouseClicked

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void second_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_second_tableMouseClicked
        // TODO add your handling code here:
        int rowNum_first_table;
        int row_num_sec_table=second_table.getSelectedRow();
        //second table when sellection.
        String place=second_table.getValueAt(row_num_sec_table, 0).toString();
        String price=second_table.getValueAt(row_num_sec_table, 1).toString();
        String Date=second_table.getValueAt(row_num_sec_table, 2).toString();
        String time=second_table.getValueAt(row_num_sec_table, 3).toString();
        String id_num=second_table.getValueAt(row_num_sec_table,4).toString();
        String passport=second_table.getValueAt(row_num_sec_table, 5).toString();
        this.ID.setText(id_num);
        this.place.setText(place);
        this.date.setText(Date);
        this.time.setText(time);
        this.price.setText(price);    
        this.passport.setText(passport);
        ///first table->  ↓
        for (int i=0;;i++)
        {
        if(passport.equals(first_table.getValueAt(i, 2).toString()))
        {
        rowNum_first_table=i;
        break;
        }       
        }
        String name=first_table.getValueAt(rowNum_first_table, 0).toString();
        String phone=first_table.getValueAt(rowNum_first_table,1).toString();

        user_name.setText(name);        
        this.phone.setText(phone);
        

    }//GEN-LAST:event_second_tableMouseClicked

    private void passportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passportActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            int row_num_sec_table;
       Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/airport","root","root");
       PreparedStatement prep=con.prepareStatement("update userdata set username=?,phone=? where passport_number=?");
       PreparedStatement prep2=con.prepareStatement("update user_order set place=?,price=?,date_reserved=?,time_reserved=? where id_num=?");
       String place=this.place.getText();
       String id_num=this.ID.getText();
       String price=this.price.getText();
       String Date=this.date.getText();
       String time=this.time.getText();
       String name=user_name.getText();
       String phone=this.phone.getText();
       String passport=this.passport.getText();
        prep.setString(1,name);       
        prep.setString(2,phone); 
        prep.setString(3, passport);
        //////////////////////////////////////     
                
        prep2.setString(1,place);
        
        prep2.setString(2, price);        

        prep2.setString(3, Date);
               
        prep2.setString(4, time); 
        
        prep2.setString(5, id_num);
        
        prep2.executeUpdate();
        prep.executeUpdate();
        jButton4ActionPerformed(evt);
        

        } catch (SQLException ex) {
            System.out.println("Error");
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
        Fram1 f1=new Fram1();
        f1.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
       Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/airport","root","root");
       PreparedStatement prep=con.prepareStatement("select*from userdata");
       PreparedStatement prep2=con.prepareStatement("select*from user_order");
       String passport=this.passport.getText();
         
       ResultSet set=prep.executeQuery();
       ResultSet set2=prep2.executeQuery();
       
       boolean notfound=true;
       while(set.next()){
           if(set.getString(3).toString().equals(passport)){
         String row[]={set.getString(1),set.getString(2)}; 
         this.user_name.setText(row[0]);
         this.phone.setText(row[1]);
         notfound=false;
         break;
           }
           else 
               continue;
       }      
       while(set2.next()){
           if(set2.getString(6).toString().equals(passport)){
         String row[]={set2.getString(1),set2.getString(2),set2.getString(3),set2.getString(4),set2.getString(5)}; 
         this.place.setText(row[0]);
         this.price.setText(row[1]);
         this.date.setText(row[2]);
         this.time.setText(row[3]);
         this.ID.setText(row[4]);
         notfound=false;
         break;
           }
           else 
               continue;
       }      
       ///////////////////////////////////
       
      if(notfound){
      JOptionPane.showMessageDialog(this,"He/she is not found");
      }

       
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error");
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fram4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fram4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fram4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fram4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fram4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField date;
    private javax.swing.JTable first_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField passport;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField place;
    private javax.swing.JTextField price;
    private javax.swing.JTable second_table;
    private javax.swing.JTextField time;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables

    private void jButton4ActionPerformed(MouseEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
