import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.jar.JarFile;

import java.sql.*;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Fram3 extends javax.swing.JFrame {

    /**
     * Creates new form Fram3
     */
    public Fram3() {
        initComponents();
        setSize(885, 400);
        setResizable(false);
        setLocation(280,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        passport = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        places = new javax.swing.JComboBox<>();
        time = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("Delete reserve");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(680, 310, 160, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setText("user name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setText("passport number:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 204));
        jLabel3.setText("phone:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 130, 80, 30);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(190, 20, 260, 30);
        getContentPane().add(phone);
        phone.setBounds(190, 130, 260, 30);
        getContentPane().add(passport);
        passport.setBounds(190, 70, 260, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 153));
        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 320, 70, 30);

        places.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sharm elshakh", "Alex", "Aswan", "Ciro", "Giza" }));
        places.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                placesItemStateChanged(evt);
            }
        });
        places.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                placesMouseDragged(evt);
            }
        });
        places.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                placesMouseClicked(evt);
            }
        });
        places.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placesActionPerformed(evt);
            }
        });
        getContentPane().add(places);
        places.setBounds(500, 40, 120, 30);

        time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeMouseClicked(evt);
            }
        });
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        getContentPane().add(time);
        time.setBounds(760, 40, 60, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("place:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 10, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Date:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(650, 20, 80, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Time:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(760, 20, 80, 20);

        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        getContentPane().add(Date);
        Date.setBounds(650, 40, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("price:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 200, 50, 40);

        price.setEnabled(false);
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price);
        price.setBounds(80, 210, 120, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 204));
        jButton5.setText("confirm");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(280, 310, 320, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder/img12.JPG"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(4, 0, 870, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try{

            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/airport","root","root");
            PreparedStatement prep=con.prepareStatement("delete from userdata where passport_number=?");
            PreparedStatement prep2=con.prepareStatement("delete from user_order where passport_num=?");

            String passport=this.passport.getText();

            prep.setString(1, passport);

            prep2.setString(1, passport);

            prep2.executeUpdate();
            prep.executeUpdate();
            JOptionPane.showMessageDialog(this, "your reservation has been removed");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "there is no reservation");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_usernameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        Fram1 f1=new Fram1();
        f1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void placesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_placesItemStateChanged
        // TODO add your handling code here:
         if(places.getSelectedItem().toString().equals("Alex"))
        {
            price.setText("2000");
        }
        else if(places.getSelectedItem().toString().equals("Sharm elshack"))
        {
            price.setText("3000");
        }
        else if(places.getSelectedItem().toString().equals("Aswan"))
        {
            price.setText("6000");
        }
        else if(places.getSelectedItem().toString().equals("Ciro"))
        {
            price.setText("2500");
        }
        else
        {   
          price.setText("5000");
        }
    }//GEN-LAST:event_placesItemStateChanged

    private void placesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placesMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_placesMouseClicked

    private void placesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placesActionPerformed
        // TODO add your handling code here:
          if(places.getSelectedItem().toString().equals("Alex"))
        {
            price.setText("2000");
        }
        else if(places.getSelectedItem().toString().equals("Sharm elshack"))
        {
            price.setText("3000");
        }
        else if(places.getSelectedItem().toString().equals("Aswan"))
        {
            price.setText("6000");
        }
        else if(places.getSelectedItem().toString().equals("Ciro"))
        {
            price.setText("2500");
        }
        else
        {   
          price.setText("5000");
        }
    }//GEN-LAST:event_placesActionPerformed

    private void timeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeMouseClicked
        // TODO add your handling code here:
        try{
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/airport","root","root");
            PreparedStatement prep=con.prepareStatement("update user_order set place=?,price=?,date_reserved=?,time_reserved where passport_num=?");
            ResultSet set=prep.executeQuery();
        }
        catch (SQLException ex) {
            //Logger.getLogger(Fram4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error");
        }
    }//GEN-LAST:event_timeMouseClicked

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_priceActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        //save data
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/airport","root","root");
            PreparedStatement prep=con.prepareStatement("insert into userdata(username,phone,passport_number)values(?,?,?)");
            PreparedStatement prep2=con.prepareStatement("insert into user_order(place,price,date_reserved,time_reserved,passport_num)values(?,?,?,?,?)");
            String place=this.places.getSelectedItem().toString();
            String price=this.price.getText();
            String Date=this.Date.getText();
            String time=this.time.getSelectedItem().toString();
            String passport=this.passport.getText();
            String username=this.username.getText();
            String phone=this.phone.getText();
            //insert in the first table
            prep.setString(1, username);
            prep.setString(2, phone);
            prep.setString(3, passport);

            //insert in the second table
            prep2.setString(1, place);
            prep2.setString(2, price);
            prep2.setString(3, Date);
            prep2.setString(4, time);
            prep2.setString(5, passport);
            prep.executeUpdate();
            prep2.executeUpdate();
            JOptionPane.showMessageDialog(this, "your reservation has been done SUCCESSFULLY");

        } catch (SQLException ex) {
            //Logger.getLogger(Fram4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error_in saving");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void placesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placesMouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_placesMouseDragged

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fram3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fram3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fram3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fram3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fram3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField passport;
    private javax.swing.JTextField phone;
    private javax.swing.JComboBox<String> places;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> time;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
